task: detection

num_classes: 1
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: PotholeDataset
    img_folder: /content/dataset/YOLOv8/groundOnly_pothole/images/train
    ann_folder: /content/dataset/YOLOv8/groundOnly_pothole/labels/train
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: PotholeDataset
    img_folder: /content/dataset/YOLOv8/groundOnly_pothole/images/val
    ann_folder: /content/dataset/YOLOv8/groundOnly_pothole/labels/val
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False